# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-12-05 03:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_lair', '0002_user_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datum',
            name='modified',
        ),
        migrations.AlterField(
            model_name='datum',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
